import Head from 'next/head';
import Link from 'next/link';

export async function getStaticProps () {
    const res = await fetch(`${process.env.NEXT_PUBLIC_BACKEND_URL}/api/books`)
    
    const data = await res.json()
    
    return {
        props: {
            books: data
        }
    }
}

const BookList = ({ books }) => {
    function handeDelete() {

    }
    return (
        <div>
            <Head>
                <title>Books App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <h1>Libros</h1>
            <ul>
                { books.map(book => (
                    <li key={`book-${book.id}`}>
                        <Link href={`/libros/${book.id}`}>{book.title}</Link>
                        {' - '}
                        <Link href={`/libros/${book.id}/editar`}>Editar</Link>
                        {' - '}
                        <form onsubmit={handeDelete}
                            style={{ display: "inline" }}>
                            <button>Eliminar</button>
                        </form>
                    </li>
                )) }
            </ul>
            <Link href="/libros/crear">Crear libro</Link>
        </div>
    );
};

export default BookList;